### ISSUE TITLE
Ejemplos de como configurar y utilizar el modulo

### ISSUE THREAD

**Issue by aek** [csrocha/odoo_fpoc#4]
Seria bueno tener una referencia de como utilizar y configurar el modulo y sus funcionalidades internas, su integracion con las funcionalidades de fpoc-chrome y posibles extensiones para posibles contribuciones

**Comment by csrocha** [comment]
@aek gracias por tu comentario. ¿Cómo te gustaría participar? Aceptaría ayuda para realizar esta documentación.

**Comment by aek** [comment]
Hola estuve viendo los modulos que ha hecho para las impresoras fiscales y mas bien lo que hice fue adaptarlos pues no me servian para ese modelo de bixolon tal y como estan. Le ajuste para poder utilizar el utilitario de TFHKA por carecer de documentacion de esa impresora en especifico. Luego me llego el manual de comandos de la impresora y se puede implementar en js pero difiere mucho de lo que tienes implementado para el protocolo de epson esc/pos

**Comment by csrocha** [comment]
@aek, mandame la documentación. Intenté que la API sea lo más independiente del modelo posible.

**Comment by rzavarce** [comment]
Hola saludos cordiales, estoy interesado en colaborar con la documentación para utilizar y configurar el modulo y sus funciones internas, la verdad estoy iniciando en el mundo de las impresoras fiscales y quieras crear el soporte para las impresoras Bixolon o Aclas en Venezuela. Si pudieran darme concejos de implementación y pautas de desarrollo seria mucha utilidad. Yo iré creando la documentación mientras voy desarrollando el modulo. Espero por su pronta respuesta.

**Comment by csrocha** [comment]
@rzavarce , ¿quieres crear un issue por cada impresora que quieras implementar? Por supuesto voy a  ayudar a implementarlo.

**Comment by csrocha** [comment]
Cierro la discusión porque no he recibido ningún requerimiento bien definido para implementar.
