### ISSUE TITLE
Connection problem with openerp server can't complete database list call

### ISSUE THREAD

**Issue by pronexo-argentina** [csrocha/odoo_fpoc#7]
Hola, he instalado el módulo en un odoo pero no logro que listen las bases de datos. Cuando intento conectar me sale un error: Connection problem with openerp server can't complete database list call

Quisiera saber si hay que configurar algo adicional. He instalado el modulo sin problemas en otras instalaciones de odoo. Ésta en particular está utilizando docker. Te dejo la captura de la pantalla con el error que me da la aplicación de chrome.

Saludos

![captura de pantalla 2015-10-30 14 49 08 3](https://cloud.githubusercontent.com/assets/11078121/10855229/31ae37ea-7f1f-11e5-91d2-1119f3a56397.png)

**Comment by csrocha** [comment]
Pregunta, que versión de Odoo usas?

**Comment by pronexo-argentina** [comment]
8.0

**Comment by csrocha** [comment]
@ragher Tienes el acceso al Log del Odoo para enviarme el momento en que intenta conectarse el odoo_fpoc a Odoo?

**Comment by pronexo-argentina** [comment]
Hola., te paso el log.

ERROR None openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 537, in handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1413, in _dispatch_nodb
func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1430, in match
raise NotFound()
NotFound: 404: Not Found

**Comment by csrocha** [comment]
Tienes instalado el módulo:

https://github.com/csrocha/odoo_fpoc

?

**Comment by pronexo-argentina** [comment]
Si claro, lo tengo instalado

**Comment by csrocha** [comment]
@ragher , ¿tu servidor está detrás de un proxy reverso? (¿apache o ngnix?)

Si es así fijate el siguiente documento:
https://www.odoo.com/forum/help-1/question/problem-when-forcing-http-to-pos-session-67931

**Comment by csrocha** [comment]
@ragher , tu problema es la última barra invertida de la URL. Si la quitas, funciona.

Ahora estoy resolviendo este problema para que no vuelva a ocurrir.

**Comment by csrocha** [comment]
Resuelto en https://github.com/csrocha/fpoc-chrome/issues/8
