### ISSUE TITLE
Instalar en Odoo v9.0

### ISSUE THREAD

**Issue by efarias** [csrocha/odoo_fpoc#8]
Hola, primero felicitarte por tu aporte con éste módulo.

Quisiera saber si hay alguna indicación para instalarlo en Odoo v9 o si tienes planes de migrarlo pronto.

Saludos!

**Comment by csrocha** [comment]
Disculpa la demora @efarias , no he probado en la versión 9. No debería existir cambios por lo que entiendo. ¿Quieres probar y decir que que problemas y errores obtienes? Crea issues aquí para poder ir administrándolos. Gracias.

**Comment by dansanti** [comment]
Hola! podrías de favor , abrir un branch para la versión 9 y así poder hacer un commit con los cambios para la versión 9?, son algunos pocos para que quede instalable en odoo9

**Comment by csrocha** [comment]
@dansanti , has un fork y realiza todos los cambios ahí. Luego has un merge request a la version master. De ahí creo directamente el nuevo branch.

**Comment by xub** [comment]
hola como van? alguna noticia para la V9 ? pruebo de instalar ? o ya tienen algo ? saludos
